In [13]:
#Gathering Data manually from google

In [14]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [15]:
#path to directory with images-- /content/drive/MyDrive/Python and DS/Minor Project/images

In [16]:
#preprocessing data

import os 
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

target = []
images = []
flat_data = []

DATADIR = "/content/drive/MyDrive/Python and DS/Minor Project/images"
CATEGORIES = ["rose","tree"]
for category in CATEGORIES:
  class_num = CATEGORIES.index(category)
  path = os.path.join(DATADIR,category)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    #plt.imshow(img_array)
    img_resized = resize(img_array,(150,150,3))
    flat_data.append(img_resized.flatten())
    target.append(class_num)

flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size=0.2,random_state=42, stratify=target)

In [18]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm 
param_grid = [
           
          {'C':[1,10,100,1000],'kernel': ['linear']},
          {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']}
           
]

svc = svm.SVC(probability=True)
model = GridSearchCV(svc,param_grid)
model.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [19]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [20]:
y_test

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [22]:
accuracy_score(y_pred , y_test)

1.0

In [23]:
confusion_matrix(y_pred,y_test)

array([[6, 0],
       [0, 5]])

In [ ]:
#Testing image without deployment

flat_data=[]
url = input("Enter your URL")
img = imread(url)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out = CATEGORIES[y_out[0]]
print(f"Predicted Output: {y_out}")
q = model.predict_proba(flat_data)
for index,item in enumerate(CATEGORIES):
      print(f"{item} : {q[0][index]*100}%")